###################################################################
#
# Submit a PCSF-TPS pipeline on permuted prizes using the parameters
# set in the wrapper script.
# Assumes a shared file system and does not transfer files.
# 
###################################################################

Executable = pcsf/run_permuted_pipeline.sh
Universe = vanilla

# Disable notifications for now
Notification = Never

Output = $ENV(outpath)/$(Cluster).$(Process).out
Error = $ENV(outpath)/$(Cluster).$(Process).err  
Log = $ENV(outpath)/$(Cluster).$(Process).log

# Use a single thread for each run of Forest
Request_cpus = 1
Request_memory = 1GB
Request_disk = 1GB

# Copy environment variables set in the submission wrapper script to
# the execute node's environment
Getenv = True
# Also copy the Cluster and Process and the machine that runs the job
Environment = "cluster=$(Cluster) process=$(Process) runningon=$$(Name)"

# Submit multiple copies of the pipeline, one for each copy of the permuted
# peptide map.  Each instance of the PCSF-TPS pipeline will run on a different
# copy of the permuted peptide map.
Queue $ENV(permutecopies)
#END
