#!/bin/bash

TIME_SERIES_FILE=$1
MAPPING_FILE=$2
FOLD_CHANGE_THRESHOLD=$3

sbt \
  "project tps-core" \
  "run-main tps.evaluation.SignificanceScoreAndPrizeProducer $TIME_SERIES_FILE $MAPPING_FILE $FOLD_CHANGE_THRESHOLD"
