#!/bin/bash

NETWORK_FILE=$1
MAPPING_FILE=$2
P_VAL_THRESHOLD=$3
MAX_NB_EDGES=$4

sbt \
  "project tps-core" \
  "run-main tps.evaluation.funchisq.FunChisq2SIFConverter $NETWORK_FILE $MAPPING_FILE $P_VAL_THRESHOLD $MAX_NB_EDGES"
